# -*- coding: utf-8 -*-
"""support.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15tBs_cg5rviQ6DtBbzL3qVS4shDrD9b6

PIPELINE DE HYBRID SEARCH PARA UN SISTEMA DE SOPORTE TÉCNICO EMPRESARIAL

Data Ingestion

Carga de la documentación
"""

from google.colab import files

uploaded = files.upload()

import os

os.listdir()

"""Extracción de texto a través de librería LangChain"""

!pip install langchain langchain-community pypdf
from langchain_community.document_loaders import PyPDFLoader

loader = PyPDFLoader("Technical Support Solutions Handbook SPANISH MX2.pdf")

documents = loader.load()

len(documents)

"""Chunking"""

from langchain_text_splitters import RecursiveCharacterTextSplitter

splitter = RecursiveCharacterTextSplitter(
    chunk_size=500,
    chunk_overlap=100
)

chunks = splitter.split_documents(documents)

print(len(chunks))

print(chunks[29].page_content)

"""Generación de embeddings"""

!pip install sentence-transformers langchain-huggingface
from langchain_huggingface import HuggingFaceEmbeddings
embeddings = HuggingFaceEmbeddings(
    model_name="sentence-transformers/all-MiniLM-L6-v2"
)

vector = embeddings.embed_query(chunks[0].page_content)

print(vector[:10])

"""Indexación vectorial a tarvés de FAISS para búsquedas semánticas"""

!pip install faiss-cpu
from langchain_community.vectorstores import FAISS

vectorstore = FAISS.from_documents(
    chunks,
    embeddings
)

query = "Problema con el Hardware"

results = vectorstore.similarity_search(query, k=3)

for r in results:
    print(r.page_content)
    print("------")

"""Indexación keyword retrieval o búsqueda por palabras clave, a través de BM25Retriever de LangChain"""

!pip install rank_bm25
from langchain_community.retrievers import BM25Retriever
bm25_retriever = BM25Retriever.from_documents(chunks)

results = bm25_retriever.invoke(
    "Problema con el Hardware"
)
for r in results[:3]:
    print(r.page_content)
    print("------")

"""Hybrid search

Búsqueda semántica
"""

faiss_results = vectorstore.similarity_search(
    "Problema con el Hardware",
    k=3
)

"""Búsqueda por palabras clave"""

bm25_results = bm25_retriever.invoke(
    "Problema con el Hardware"
)

"""Combinación"""

hybrid_results = faiss_results + bm25_results[:3]

"""Eliminar duplicados"""

unique_results = []

seen = set()

for doc in hybrid_results:
    if doc.page_content not in seen:
        unique_results.append(doc)
        seen.add(doc.page_content)

"""Resultados híbridos"""

for r in unique_results[:5]:
    print(r.page_content)
    print("------")

"""Re-ranking con CrossEncoder"""

!pip install sentence-transformers
from sentence_transformers import CrossEncoder
reranker = CrossEncoder(
    'cross-encoder/ms-marco-MiniLM-L-6-v2'
)

query = "Problema con el Hardware"

pairs = [
    (query, doc.page_content)
    for doc in unique_results
]

scores = reranker.predict(pairs)

ranked_results = list(zip(scores, unique_results))

ranked_results = sorted(
    ranked_results,
    key=lambda x: x[0],
    reverse=True
)

for score, doc in ranked_results[:3]:
    print("Score:", score)
    print(doc.page_content)
    print("------")